package:
    name: nelpy
    version: "0.2.1"

source:
    git_url: https://github.com/nelpy/nelpy.git

build:
    script: python setup.py install
    number: 1

requirements:
  build:
    - python
    - setuptools
    - numpy x.x
    - scipy
    - matplotlib
    - dill
    - scikit-learn

  run:
    - python
    - python
    - numpy x.x
    - scipy
    - matplotlib
    - dill
    - scikit-learn
